# Header Menu. title: link
menu:
  About: /about
  Github: https://github.com/Fechin
  Twitter: https://twitter.com/FechinLi


# 查看文章时是否自动播放音乐
autoplay: true
# 博客文章默认音乐, 优先级: 1.文章头mp3参数> 2.在这里配置
mp3: http://link.hhtjim.com/163/425570952.mp3
# 首页封面图, 优先级: 1.在这里配置> 2.文章头cover参数;
welcome_cover: /img/welcome-cover.jpg
# 文章封面图, 优先级: 1.文章头cover参数 > 2.在这里配置
cover: /img/cover.jpg


keywords: 
# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 
# 网站ico
favicon: /img/favicon.png
rss: atom.xml
